spring:
  profiles:
    active: dev
    
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
logging.config: ./config/logback-spring.xml

email:
  emailUrl: http://www.amardata.com/crservice/AmarNotifyService/initEvent

http:
  proxy:
    enable: true
    ip: 172.16.72.173
    port: 3128
    schema: http
  

      